# containers
# original container (will work prior to updating the plottting script)
#containerized: "docker://dah0303/wastewater:latest"

# current container
containerized: "docker://lunnwa/snowa:latest"

pre_qc:
  copy_runs: "n"
  directory: "new_runs/" # this should be the file path for new_runs as a string, and the snakefile 'param' section should grab the value from this key

merge_data:
  directory: "runs/"

add_sites_and_classes:
  sites: "defaults/sample_site-counties.csv"
  classifications: "defaults/ww_lineage_classifications.csv"

# geographic data files for maps
geographic_data:
  shapefiles_dir: "defaults/"
  non_sampled_counties: "defaults/non_sampled_counties.csv"

plots:
  plot_dir: "results/plots/"
    #######################################
  # SET TIMEFRAME FOR EACH OF THE PLOTS

  # Default timeframe for stacked bar plot and bubble plot (1 year)
  # Default timeframe for line graph, heatmap, and weekly maps (12 weeks)

  # You can set date parameters by recency or date_range (choose one or other)

  # SPECIFYING RECENCY PARAMETER
  # plot_name:
  #   timeframe:
  #     recency:
  #       value: 1
  #       unit: year # Valid units are: day, week, month, year (singular or plural)

  # SPECIFYING DATE PARAMETER
  # plot_name:
  #   timeframe:
  #     date_range:
  #       start_date: 2024-01-01
  #       end_date:   2024-06-30
  filter:
  # date parameters for weekly variant proportions (stacked bar plot)
    stacked_bar_plt:
      timeframe:
        recency:
          value: 1
          unit: year

    # date parameters for QC timeline of detections (QC presence/absence plot)
    qc_pa_plt:
      timeframe:
        recency:
          value: 1
          unit: year

    # date parameters for timeline of detections (bubble plot)
    bubble_plt:
      timeframe:
        recency:
          value: 1
          unit: year

    # date parameters for top 3 variants (line plt)
    line_plt:
      timeframe:
        recency:
          value: 12
          unit: weeks

    # date parameters for heatmap of prevalent variants (heatmap)
    heatmap_plt:
      timeframe:
        recency:
          value: 12
          unit: weeks

    # date parameters for map of dominant variants (weekly maps)
    weekly_maps_plt:
      timeframe:
        recency:
          value: 12
          unit: weeks


report:
  format: "pdf"
  date: "July 2026"
  report_generator: "Steph M Lunn, MPH, MS"
  report_generator_email: "stephanie.lunn@doh.wa.gov"
  team: "Molecular Epidemiology Program"
  team_email: "wgs-epi@doh.wa.gov"
  data_period: "July 2025 - July 2026"